name: wallify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  device_preview: ^1.1.0

  google_fonts: null

  internet_connection_checker_plus: ^2.5.1
  cached_network_image: ^3.4.0

  cupertino_icons: null
  provider: null
  flutter_staggered_grid_view: null
  google_nav_bar: null
  dot_navigation_bar: null
  popover: ^0.3.0+1

  http: null
  html_unescape: ^2.0.0
  flutter_file_dialog: null

  dio: null
  path_provider: null
  # open_file: 
  hive: ^2.2.3
  hive_flutter: null

  gallery_saver_updated: ^3.0.0

  flutter_wallpaper_manager: null
  async_wallpaper: ^2.0.3

  flutter_cache_manager: null
  # uuid: 
  # sqflite: 
  # rxdart: 
  # path: 
  # collection: 
  # clock: 
  share_plus: null
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  # url_launcher_linux: 
  # url_launcher_platform_interface: 
  # cross_file: 
  # ffi: 
  # file: 
  # meta: 
  # mime: 
  # share_plus_platform_interface: 
  # url_launcher_web: 
  # url_launcher_windows: 
  # web: 
  # win32: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  hive_generator: null
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/logo_icons/
    - assets/images/
    - assets/icons/
    - assets/
flutter_intl:
  enabled: true
