// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDb-t6gjpCVO5IgqC-TKYpaQxpdsAD17Y',
    appId: '1:871738769118:android:6cdbad66a9c4f391880c4f',
    messagingSenderId: '871738769118',
    projectId: 'wallify-f8ca6',
    storageBucket: 'wallify-f8ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJxXSDwVLza_acVtLEY3GTjn_4Q0Udkc',
    appId: '1:871738769118:ios:e5e55c82c217618f880c4f',
    messagingSenderId: '871738769118',
    projectId: 'wallify-f8ca6',
    storageBucket: 'wallify-f8ca6.appspot.com',
    iosBundleId: 'com.example.wallify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsoZ1jyMyLXxIniv2SCYqh_Tn19amaZ8',
    appId: '1:871738769118:web:352bcc5eebc6047b880c4f',
    messagingSenderId: '871738769118',
    projectId: 'wallify-f8ca6',
    authDomain: 'wallify-f8ca6.firebaseapp.com',
    storageBucket: 'wallify-f8ca6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJxXSDwVLza_acVtLEY3GTjn_4Q0Udkc',
    appId: '1:871738769118:ios:e5e55c82c217618f880c4f',
    messagingSenderId: '871738769118',
    projectId: 'wallify-f8ca6',
    storageBucket: 'wallify-f8ca6.appspot.com',
    iosBundleId: 'com.example.wallify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARsoZ1jyMyLXxIniv2SCYqh_Tn19amaZ8',
    appId: '1:871738769118:web:27a3cb1360376e5a880c4f',
    messagingSenderId: '871738769118',
    projectId: 'wallify-f8ca6',
    authDomain: 'wallify-f8ca6.firebaseapp.com',
    storageBucket: 'wallify-f8ca6.appspot.com',
  );

}